[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Mixstable"
version = "0.1.7"
description="Parameter estimation tools for one-dimensional stable distributions and their mixtures.",
readme = "README.md"
authors = [
    {name = "Solym Manou-Abi"}
    {name = "Adam Najib"}
    {name = "Yousri Slaoui"}
]
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "matplotlib",
    "scikit-learn",
    "streamlit",
    "statsmodels",
    "rpy2"
]

[tool.setuptools.packages.find]
where = ["src"]
